import { PROFILES } from '../catalog.js';
import { escapeHtml as e } from '../sanitize.js';
import { renderMarkdown } from '../markdown.js';
const readmes=import.meta.glob('../../../defaults/profiles/*/*/README.md',{query:'?raw',import:'default',eager:true});
const artifacts=Object.keys(import.meta.glob('../../../defaults/profiles/**/*',{query:'?raw',import:'default'}));
export function renderProfiles(selected) {
  const profile=PROFILES.find(p=>p.id===selected);
  if (!profile) return `<section class="profile-directory"><p class="eyebrow">REUSABLE FRAMEWORK PACKS</p><h1>Skills & profiles</h1><p>Choose a profile to see its purpose, included templates, composition rules and installation. Community skills use SKILL.md; a profile composes project defaults around them.</p><div class="project-card-grid">${PROFILES.map(p=>`<button class="profile-detail-card" data-profile-id="${p.id}"><span class="eyebrow">${p.kind==='base'?'Base profile':'Optional modifier'}</span><h2>${p.id}</h2><p>${p.description}</p><span>Explore contents →</span></button>`).join('')}</div><section class="insight-panel"><h2>Publish your own skill pack</h2><p>Use standard SKILL.md instructions and an sdd-pack.json composition manifest. Validate a local pack before installing it; updates protect local edits.</p><code>bash scripts/skills.sh pack validate /path/to/pack</code><p><a href="https://github.com/ThisIsPhila/Spec-Driven-Development-Framework/blob/feat/phase-005-visual-framework-workspace/docs/community-skill-packs.md" target="_blank" rel="noopener noreferrer">Community pack format and examples ↗</a></p></section></section>`;
  const folder=`${profile.kind==='base'?'base':'modifiers'}/${profile.id}/`;
  const doc=Object.entries(readmes).find(([key])=>key.includes(folder))?.[1] || '';
  const included=artifacts.filter(key=>key.includes(folder)).map(key=>key.split(folder)[1]).filter(file=>file!=='README.md');
  const command=`bash .sdd-framework/scripts/setup.sh --profile ${profile.kind==='base'?profile.id:'general+'+profile.id}`;
  return `<section class="profile-detail"><button class="btn btn-secondary" data-profile-back>← All skills & profiles</button><p class="eyebrow">${profile.kind==='base'?'BASE PROFILE':'OPTIONAL MODIFIER'}</p><h1>${profile.id}</h1><p>${profile.description}</p><div class="insights-grid"><section class="insight-panel"><h2>Use this profile</h2><p>After cloning the framework into .sdd-framework in your project:</p><pre><code>${e(command)}</code></pre><button class="btn btn-secondary" data-copy-command="${e(command)}">Copy setup command</button><p>${profile.kind==='base'?'Choose one base profile; optional modifiers add specialist rules.':'Compose this modifier with a base profile. It is not a standalone base.'}</p><h2>Included files (${included.length})</h2><ul>${included.map(file=>`<li>${e(file)}</li>`).join('')}</ul></section><section class="insight-panel"><h2>What this provides</h2><div class="markdown-body">${renderMarkdown(doc.replace(/^---\n[^]*?\n---\n/,''))}</div></section></div></section>`;
}
