import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { LocalProjectService } from '../../server/service.js';
import { AccountService } from '../../server/account-service.js';
let service, accountService, root, info, accountInfo;
test.beforeAll(async () => {
  root = fs.mkdtempSync(path.join(os.tmpdir(),'sdd-browser-'));
  for (let i=1;i<=60;i++) {
    const id=String(i).padStart(3,'0'); const folder=path.join(root,`.sdd/specs/active/phase-${id}-example`);
    fs.mkdirSync(folder,{recursive:true});
    fs.writeFileSync(path.join(folder,'requirements.md'),`# Project phase ${i}\n**Status:** Approved\n### REQ-${id}.1: Functional behavior\n`);
    fs.writeFileSync(path.join(folder,'tasks.md'),`# Tasks\n- [x] **[T${id}.1]** Completed task\n  - **Objective:** REQ-${id}.1\n- [ ] **[T${id}.2]** Pending task\n  - **Objective:** REQ-${id}.1\n`);
  }
  fs.mkdirSync(path.join(root,'graphify-out'));
  fs.mkdirSync(path.join(root,'.sdd/evidence/phase-001-example'),{recursive:true});
  fs.writeFileSync(path.join(root,'.sdd/evidence/phase-001-example/reference-note.md'),'# Reference note\nREQ-001.1 T001.1\nNo recorded verification outcome.\n');
  fs.writeFileSync(path.join(root,'.sdd/specs/active/phase-001-example/design.md'),'# Design\n```mermaid\nflowchart LR\n Files[Markdown files] --> Extractor --> Viewer[Visual workspace]\n```\n');
  fs.writeFileSync(path.join(root,'graphify-out/graph.json'),JSON.stringify({nodes:[{id:'source',label:'Source file',type:'file'},{id:'parser',label:'Task parser',type:'function'}],edges:[{from:'source',to:'parser',label:'calls',provenance:'EXTRACTED'}]}));
  service = new LocalProjectService({port:0,staticDir:path.resolve('dist')}); service.registerProject(root); info=await service.start();
  accountService = new AccountService({database:':memory:',port:0,staticDir:path.resolve('dist')}); accountInfo=await accountService.start();
});
test.afterAll(async () => { await service.stop(); await accountService.stop(); fs.rmSync(root,{recursive:true,force:true}); });
test('public page stays contained at mobile, tablet and desktop widths',async ({page})=>{
  for (const width of [320,390,768,1024,1440]) {
    await page.setViewportSize({width,height:844}); await page.goto(`http://127.0.0.1:${info.port}/`);
    await expect(page.getByText('Explore fictional projects')).toBeVisible();
    await expect(page.locator('body')).not.toContainText('undefined');
    await expect(page.locator('.profile-catalog-table .agent-brand-icon svg')).toHaveCount(10);
    const overlaps=await page.locator('.profile-title-line').evaluateAll(lines=>lines.filter(line=>{
      const icon=line.querySelector('.agent-brand-icon').getBoundingClientRect();
      const name=line.querySelector('.profile-name').getBoundingClientRect();
      return icon.right>name.left+0.5;
    }).length);
    expect(overlaps,`overlapping profile labels at ${width}`).toBe(0);
    const overflow=await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth,offenders:[...document.querySelectorAll('*')].filter(el=>el.getBoundingClientRect().right>innerWidth+0.5 && el.getBoundingClientRect().width<innerWidth*2).slice(0,8).map(el=>({tag:el.tagName,class:String(el.className),right:el.getBoundingClientRect().right}))}));
    expect(overflow.document,`page-wide overflow at ${width}`).toBeLessThanOrEqual(overflow.viewport);
  }
  if (process.env.SDD_REVIEW_SCREENSHOTS) await page.screenshot({path:path.join(os.tmpdir(),'sdd-reviewed-catalog.png')});
  await page.locator('#launch-demo-btn').click();
  await page.getByRole('button',{name:'Explore phases',exact:true}).click();
  await page.locator('[data-phase-tab="requirements"]').click();
  await page.locator('button[data-source-path]').first().click();
  await expect(page.locator('dialog pre')).toContainText('REQ-');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.locator('.phase-subtabs-bar [data-phase-tab="overview"]').click();
  await page.locator('.phase-subtabs-bar [data-phase-tab="traceability"]').click();
  await expect(page.getByRole('img',{name:'Traceability Graph',exact:true})).toBeVisible();
  if (process.env.SDD_REVIEW_SCREENSHOTS) await page.screenshot({path:path.join(os.tmpdir(),'sdd-reviewed-graph.png')});
  expect(await page.locator('.traceability-svg .edges-group path').count()).toBeGreaterThan(0);
  await expect(page.locator('.traceability-list')).toContainText('Referenced evidence:');
  await page.reload();
  await expect(page.getByRole('img',{name:'Traceability Graph',exact:true})).toBeVisible();
});
test('real 60-phase workspace filters tasks and follows requirement/source links',async ({page})=>{
  await page.goto(info.url);
  await page.getByRole('button',{name:'Explore phases',exact:true}).click();
  await expect(page.locator('.phase-nav-sidebar [data-phase-select]').first()).toBeVisible();
  // Navigator selection uses the actual markup rather than synthetic demo state.
  await expect(page.locator('.phase-nav-sidebar [data-phase-select]')).toHaveCount(60);
  await page.locator('#phase-search-field').fill('T060.1');
  await expect(page.locator('.phase-nav-sidebar [data-phase-select]')).toHaveCount(1);
  await page.locator('#phase-search-field').fill('');
  await expect(page.locator('.phase-nav-sidebar [data-phase-select]')).toHaveCount(60);
  const phaseButton=page.locator('.phase-nav-sidebar [data-phase-select]').first();
  await phaseButton.click();
  await page.locator('.phase-subtabs-bar [data-phase-tab="traceability"]').click();
  await expect(page.locator('.traceability-list')).toContainText('reference-note.md');
  await page.locator('[data-phase-tab="design"]').click();
  await expect(page.locator('.mermaid-svg svg')).toBeVisible();
  await expect(page.locator('.mermaid-svg')).toContainText('Markdown files');
  await expect(page.locator('.mermaid-svg')).toContainText('Visual workspace');
  await page.locator('[data-phase-tab="tasks"]').click();
  await expect(page.locator('.task-card')).toHaveCount(2);
  await page.locator('.tasks-toolbar [data-filter="todo"]').click();
  await expect(page.locator('.task-card')).toHaveCount(1);
  await expect(page.locator('.task-card')).toContainText('Pending task');
  await page.locator('[data-open-ref]').first().click();
  await expect(page.locator('.markdown-body')).toContainText('Functional behavior');
  await page.locator('button[data-source-path]').first().click();
  await expect(page.locator('dialog')).toContainText('REQ-001.1');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.locator('[data-phase-tab="tasks"]').click();
  await page.locator('#phase-search-field').focus();
  const before=await page.locator('.task-card').count();
  fs.appendFileSync(path.join(root,'.sdd/specs/active/phase-001-example/tasks.md'),'\n- [ ] **[T001.3]** Automatically refreshed\n');
  await expect(page.locator('.task-card')).toHaveCount(before+1,{timeout:5000});
  await expect(page.locator('#phase-search-field')).toBeFocused();
  const deepLink=page.url(); await page.goto(deepLink);
  await expect(page.locator('[data-phase-tab="tasks"]')).toHaveClass(/active/);
  await expect(page.locator('.task-card')).toHaveCount(2);
  for (const width of [320,390,768,1024,1440]) { await page.setViewportSize({width,height:844}); const sizes=await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth,offenders:[...document.querySelectorAll('*')].filter(el=>el.getBoundingClientRect().right>innerWidth+0.5 && el.getBoundingClientRect().width<innerWidth*2).slice(0,8).map(el=>({tag:el.tagName,class:String(el.className),right:el.getBoundingClientRect().right}))})); expect(sizes.document, `workspace overflow at ${width}: ${JSON.stringify(sizes.offenders)}`).toBeLessThanOrEqual(sizes.viewport); }
  await page.locator('.project-section-rail [data-domain="knowledge"]').click();
  await expect(page.getByRole('img',{name:'Imported Graphify topology'})).toBeVisible();
  await expect(page.locator('.imported-graph rect')).toHaveCount(2);
  await expect(page.locator('.imported-graph line')).toHaveCount(1);
  fs.unlinkSync(path.join(root,'graphify-out/graph.json'));
  await expect(page.getByRole('img',{name:'Derived artifact topology'})).toBeVisible({timeout:5000});
  expect(await page.locator('.imported-graph rect').count()).toBeGreaterThan(0);
});
test('account sign-up is functional and an empty account has no invented projects',async ({page})=>{
  await page.goto(accountInfo.url);
  page.once('dialog', dialog => dialog.accept(info.url));
  await page.locator('#connect-workspace-btn').click();
  await page.getByRole('button',{name:'Explore phases',exact:true}).click();
  await expect(page.locator('.phase-nav-sidebar [data-phase-select]')).toHaveCount(60);
  await page.goto(accountInfo.url);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.locator('#account-email').fill('browser@example.test');
  await page.locator('#account-password').fill('browser-test-password');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.getByText('No connected projects yet')).toBeVisible();
  await page.getByRole('button',{name:'Account',exact:true}).click();
  await page.getByRole('button',{name:'Connect another machine',exact:true}).click();
  await expect(page.locator('dialog')).toContainText('SDD_SYNC_TOKEN=');
});

test('account access explains validation, connection failure, success and duplicate signup',async ({page})=>{
  await page.goto(accountInfo.url);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.locator('#account-error')).toContainText('valid email');
  await page.locator('#account-email').fill('feedback@example.test');
  await page.locator('#account-password').fill('short');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.locator('#account-error')).toContainText('12–256');
  await page.locator('#account-password').fill('feedback-test-password');
  await page.route('**/api/account/register',route=>route.abort());
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.locator('#account-error')).toContainText('Could not reach');
  await expect(page.getByRole('button',{name:'Create account',exact:true})).toBeEnabled();
  await expect(page.locator('#account-email')).toHaveValue('feedback@example.test');
  await page.unroute('**/api/account/register');
  await page.getByRole('button',{name:'Sign in',exact:true}).last().click();
  await expect(page.locator('#account-error')).toContainText('Email or password is incorrect');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.getByText('Account created. You are signed in.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Account',exact:true}).click();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.locator('#account-email').fill('feedback@example.test');
  await page.locator('#account-password').fill('feedback-test-password');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.locator('#account-error')).toContainText('already exists');
  await page.locator('#account-login').click();
  await expect(page.getByText('You are signed in.',{exact:true})).toBeVisible();
});

test('signed-in navigation separates projects, examples, account settings and profile details',async({page})=>{
  const privateService=new AccountService({database:':memory:',port:0,staticDir:path.resolve('dist'),bootstrapProjects:[root]});
  const privateInfo=await privateService.start();
  try {
    await page.goto(privateInfo.url);
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await page.locator('#account-email').fill('navigation@example.test');
    await page.locator('#account-password').fill('navigation-test-password');
    await page.getByRole('button',{name:'Create account',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Your projects',exact:true})).toBeVisible();
    await expect(page.locator('.project-dash-card')).toHaveCount(1);
    await page.getByRole('button',{name:'About',exact:true}).click();
    await expect(page.locator('.skills-header [data-domain]')).toHaveCount(0);
    const globalHeader = await page.locator('.skills-header').innerText();
    expect(await page.locator('.skills-hero-container').evaluate(el=>el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(await page.locator('.account-shortcuts').evaluate(el=>el.getBoundingClientRect().top));
    expect(await page.locator('.account-shortcuts').evaluate(el=>el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(await page.locator('#leaderboard').evaluate(el=>el.getBoundingClientRect().top));
    await expect(page.getByRole('button',{name:'Connect machine',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Projects',exact:true}).click();
    await expect(page.locator('dialog')).toHaveCount(0);
    await expect(page.locator('.project-dash-card')).toHaveCount(1);
    await page.getByRole('button',{name:'View project',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Next recorded work',exact:true})).toBeVisible();
    await expect(page.getByRole('img',{name:'Recorded progress by phase',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'About',exact:true}).click();
    await page.locator('[data-demo-project="1"]').click();
    await page.getByRole('button',{name:'Explore phases',exact:true}).click();
    expect(await page.locator('.skills-header').innerText()).toBe(globalHeader);
    await expect(page.getByRole('button',{name:'Detailed metrics',exact:true})).toHaveCount(0);
    const ids=await page.locator('.phase-p-tag').allTextContents();
    expect(ids.map(id=>id.trim())).toEqual(['phase-001-account-provisioning','phase-002-invoice-generation','phase-003-stripe-webhook-handling','phase-004-dunning-retry-strategy']);
    await page.getByRole('button',{name:'Projects',exact:true}).click();
    await page.getByRole('button',{name:'View project',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Next recorded work',exact:true})).toBeVisible();
    await expect(page.locator('.project-section-rail')).not.toContainText('invoice');
    await page.getByRole('button',{name:'Explore phases',exact:true}).click();
    await page.locator('.phase-list-card').first().click();
    await expect(page.getByRole('heading',{name:'Task Execution Progress',exact:true})).toBeVisible();
    await expect(page.locator('.phase-overview-graph svg.traceability-svg')).toBeVisible();
    await page.locator('.phase-overview-graph').getByRole('button',{name:'Expand graph',exact:true}).click();
    await expect(page.locator('.graph-dialog svg')).toBeVisible();
    await page.locator('.graph-dialog .trace-edge').first().focus();
    await expect(page.locator('.graph-connection-detail')).toContainText('→');
    await page.getByRole('button',{name:'Close graph',exact:true}).click();
    await expect(page.locator('.project-section-rail button svg')).toHaveCount(6);
    expect(await page.locator('.project-section-rail').evaluate(el=>el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(await page.locator('.project-content').evaluate(el=>el.getBoundingClientRect().top));
    expect(await page.locator('.skills-header').innerText()).toBe(globalHeader);
    if(process.env.SDD_REVIEW_SCREENSHOTS) await page.screenshot({path:path.join(os.tmpdir(),'sdd-phase-insights.png')});
    for (const width of [320,390,768,1024,1440]) {
      await page.setViewportSize({width,height:900});
      expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    }
    if(process.env.SDD_REVIEW_SCREENSHOTS) await page.screenshot({path:path.join(os.tmpdir(),'sdd-project-overview.png')});
    await page.getByRole('button',{name:'Skills & Profiles',exact:true}).click();
    await page.locator('[data-profile-id="web"]').click();
    await expect(page.getByRole('heading',{name:'What this provides',exact:true})).toBeVisible();
    await expect(page.locator('.profile-detail')).toContainText('accessibility-checklist.md');
    await expect(page.locator('.profile-detail')).toContainText('--profile web');
    const panels=await page.locator('.profile-reading-stack > section').evaluateAll(els=>els.map(el=>({top:el.getBoundingClientRect().top,bottom:el.getBoundingClientRect().bottom})));
    expect(panels[1].top).toBeGreaterThan(panels[0].bottom);
    await page.getByRole('button',{name:'SDD home',exact:true}).click();
    await expect(page.locator('.skills-hero-container')).toBeVisible();
    await page.getByRole('button',{name:'Skills & Profiles',exact:true}).click();
    await page.locator('[data-profile-id="web"]').click();
    await page.reload();
    await expect(page.locator('.profile-detail')).toContainText('accessibility-checklist.md');
    await page.getByRole('button',{name:'Account',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Account & connections',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Projects',exact:true}).click();
    await expect(page.locator('.project-dash-card')).toHaveCount(1);
  } finally {await privateService.stop();}
});
